alias aliases="nvim ${ZSH_CUSTOM}/alias.zsh" 
alias zshrc="nvim ~/.zshrc"
alias sshconfig="nvim ~/.ssh/config"
alias vim="nvim"
alias vi="vim"
alias ohmyzsh="nvim ${ZSH}"
alias hooks="nvim ${ZSH_CUSTOM}/hook.zsh"
alias src="omz reload"
alias update="omz update"
alias variables="nvim ${ZSH_CUSTOM}/env_variables.zsh"
alias starship_config="nvim ${HOME}/.starship/config.toml"
alias -g F="| fzf"
alias python="python3"
alias gbr="./gradlew bootrun"
alias ggj="./gradlew genJooq"
alias nrs="npm run start"
alias tf="terraform"
alias tfa="terraform apply"
alias tfi="terraform init"
alias tfp="terraform plan"
if [[ $OSTYPE='darwin'* ]]; then
    alias agi="brew install"
else
    alias agi="nocorrect sudo apt-get install"
fi
alias mackups="cd ~/dotfiles/"
alias funcs="nvim ${ZSH_CUSTOM}/function.zsh" 
